trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'example-app-test1'  # Ensure this matches your service connection name in Azure DevOps
  azureSubscription: $(AzureSubscriptionId)
  resourceGroup: 'example-test1'
  location: 'westus2'  # Correct location format
  flaskAppName: 'test-exampleapp-s3ai-version002'
  reactStorageAccount: 's3aiversion002'

jobs:
- job: DeployInfrastructure
  displayName: 'Deploy Infrastructure'
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az group create --name $(resourceGroup) --location $(location)

        # Create Storage Account for React App
        az storage account create --name $(reactStorageAccount) --resource-group $(resourceGroup) --location $(location) --sku Standard_LRS

- job: DeployFlaskApp
  dependsOn: DeployInfrastructure
  displayName: 'Deploy Flask API to Azure Web App'
  steps:
  - checkout: self

  - task: AzureCLI@2
    displayName: 'Deploy Flask API using az webapp up'
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az webapp up --name $(flaskAppName) --resource-group $(resourceGroup) --location $(location) --runtime "PYTHON:3.12" --src-path "src/backend"

- job: DeployReactApp
  dependsOn: DeployFlaskApp
  displayName: 'Build and Deploy React Application'
  steps:
  - checkout: self

  - script: |
      npm install
      npm run build
    displayName: 'Build React App'
    workingDirectory: 'src/frontend'

  - task: AzureCLI@2
    displayName: 'Deploy React App to Azure Storage'
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az storage blob upload-batch -s "$(System.DefaultWorkingDirectory)/src/frontend/build" -d '$web' --account-name $(reactStorageAccount)
